services:
  db:
    image: sberosc.sigma.sbrf.ru/docker.io/postgres:14-alpine
    container_name: sbombd
    privileged: true
    environment:
      POSTGRES_PASSWORD: password
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - sbom_pgdata:/var/run/postgresql
      - ./001_schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      args: 
        SBEROSC_TOKEN: ${SBEROSC_TOKEN}
      context: ./
      dockerfile: Dockerfile 
    container_name: sbom-serv
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    cpus: "2.0"
    mem_limit: 4048m

volumes:
  sbom_pgdata:
